## NUMPY PRACTICE EXERCISES

#### Source:
https://github.com/arewadataScience/ArewaDS-Machine-Learning/blob/main/100_numpy_exercise.md

1. Import the numpy package under the name np
2. Print the numpy version and the configuration

In [12]:
import numpy as np

# Print NumPy version and configuration
print("NumPy Version is:", np.__version__)
print("NumPy Configuration is:") 
print(np.show_config())



NumPy Version is: 1.26.2
NumPy Configuration is:
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21",
      "detection method": "pkgconfig",
      "include directory": "/Users/ruqayyanasiriro/miniconda3/envs/adsatesting/in

3. Create a null vector of size 10  
4. How to find the memory size of any array 

In [14]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)
print("Null vector of size 10:", null_vector)

# Find the memory size of any array taking null vector above as example
memory_size = null_vector.nbytes
print("Memory size of the array:", memory_size, "bytes")


Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Memory size of the array: 80 bytes


5. How to get the documentation of the numpy add function from the command line? 
   
  **ANSWER:** we use np.info(np.add). It will give the documentation of the 'add' function.
  
  
   
6. Create a null vector of size 10 but the fifth value which is 1 
   
7. Create a vector with values ranging from 10 to 49 
   
8.  Reverse a vector (first element becomes last)
   

In [17]:
import numpy as np

# Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector where 5th value is 1 =", null_vector)

# Create a vector with values ranging from 10 to 49 using np.arange()
vector_range = np.arange(10, 50)
print("\nVector with values ranging from 10 to 49 = ", vector_range)

# Reverse a vector using vector range from above
reversed_vector = np.flip(vector_range)
print("\nReversed vector is", reversed_vector)


Null vector where 5th value is 1 = [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Vector with values ranging from 10 to 49 =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed vector is [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 
    
10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
import numpy as np

# create 3x3 matrix, range 0-8
three_by_three = np.arange(0, 9).reshape(3,3)

# print result
print(three_by_three)

# given array
arr = np.array([1, 2, 0, 0, 4, 0])

#identifies the indices of elements that are non-zero.
indices_nonzero = np.nonzero(arr)

# prints output
print(indices_nonzero)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)


11.  Create a 3x3 identity matrix 
   
12.  Create a 3x3x3 array with random values

In [18]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
print("\n3x3x3 array:\n",random_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3x3 array:
 [[[0.64990161 0.93643386 0.67420505]
  [0.72361468 0.97651342 0.86096396]
  [0.88430237 0.59985661 0.82301981]]

 [[0.04475813 0.78127797 0.39957837]
  [0.95652449 0.37569051 0.06833121]
  [0.6452381  0.42273315 0.52667437]]

 [[0.13397625 0.10791948 0.0142508 ]
  [0.01976379 0.29985953 0.38714354]
  [0.77142603 0.3730331  0.90535606]]]


13.  Create a 10x10 array with random values and find the minimum and maximum values
   


In [16]:
# 10x10 array of random numbers and result
random_array_10 = np.random.rand(10,10)

print(random_array_10)

# prints min and max random generated number
print("\nmax value is",np.max(random_array_10))

print("\nmin value is",np.min(random_array_10))

[[0.72039015 0.09369841 0.72873494 0.22228938 0.06523871 0.61859414
  0.2845161  0.53928405 0.19231507 0.17979439]
 [0.95476376 0.37805859 0.17744809 0.28554068 0.73021984 0.02174129
  0.7452342  0.74529583 0.59142306 0.7688509 ]
 [0.13002406 0.68732518 0.85830626 0.33164867 0.26285724 0.9998481
  0.78274774 0.28837482 0.30349986 0.56336726]
 [0.46721595 0.51993929 0.24443317 0.80123172 0.5911429  0.04585177
  0.78965858 0.12381675 0.3533921  0.85838522]
 [0.08031602 0.27742856 0.41471596 0.54635581 0.53959118 0.32552491
  0.5469929  0.28072248 0.85583341 0.20865325]
 [0.20777889 0.38760232 0.39581088 0.70158354 0.44772252 0.35621967
  0.00200307 0.65369535 0.93456403 0.22712985]
 [0.78323234 0.06243504 0.92108338 0.3488049  0.27618782 0.36794066
  0.08020142 0.75477667 0.66412062 0.65979361]
 [0.2205282  0.07021136 0.78609665 0.68163825 0.81087067 0.50422584
  0.14202899 0.66101256 0.18697814 0.81771941]
 [0.90084349 0.66986758 0.18304613 0.72947978 0.07493001 0.11165066
  0.09381015 

14. Create a random vector of size 30 and find the mean value 
    
    

In [20]:
# Create a random vector of size 30 
random_vector = np.random.rand(30)

# prints result
print(random_vector)

# find the mean value 
mean_random_vector = np.sum(random_vector)/30

print("\nmean is:", mean_random_vector)

[0.82421224 0.70580617 0.80107379 0.03691118 0.30039325 0.46079249
 0.12953655 0.66014818 0.36088679 0.86813877 0.05934723 0.43572113
 0.49544336 0.74069737 0.10634164 0.51781306 0.98861544 0.58477368
 0.19868623 0.72809833 0.17228044 0.63112825 0.80056208 0.06001381
 0.11829353 0.76483987 0.70521921 0.1923012  0.67518834 0.76797108]

mean is: 0.49637448972654374


15. Create a 2d array with 1 on the border and 0 inside

16. How to add a border (filled with 0's) around an existing array?



In [29]:
import numpy as np

# dimensions of the 2D array as 3x3
rows, cols = 3, 3

# create a 2D array filled with zeros
array_2d = np.zeros((rows, cols))

# Set the border elements to 1
array_2d[0, :] = 1  # Top row
array_2d[-1, :] = 1  # Bottom row
array_2d[:, 0] = 1  # Leftmost column
array_2d[:, -1] = 1  # Rightmost column

print(array_2d)

# How to add a border (filled with 0's) around an existing array?
x = np.zeros((3, 3))

# Print result
print('\n Border filled with zeros\n',x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

 Border filled with zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


17. What is the result of the following expression? 

0 * np.nan  
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  
np.nan in set([np.nan])  
0.3 == 3 * 0.1  

In [30]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal  

19. Create a 8x8 matrix and fill it with a checkerboard pattern
 

In [36]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set the values 1234 just below the diagonal
matrix[1, 0] = 1
matrix[2, 1] = 2
matrix[3, 2] = 3
matrix[4, 3] = 4

print("\n5 by 5 matrix\n",matrix)

# Create an 8x8 matrix filled with zeros
cmatrix = np.zeros((8, 8), dtype=int)

# Set even rows and even columns to 1 using slicing
cmatrix[::2, ::2] = 1

# Set odd rows and odd columns to 1 using slicing
cmatrix[1::2, 1::2] = 1

print("\nchekerboard matrix\n",cmatrix)




5 by 5 matrix
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]

chekerboard matrix
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


21. Create a checkerboard 8x8 matrix using the tile function

22. Normalize a 5x5 random matrix

In [43]:
import numpy as np

# Create the checkerboard pattern
checkerboard = np.array([[0, 1], [1, 0]])

# Use np.tile() to create checkerboard pattern of 8x8 matrix
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print("Checkerboard using np.tile\n",checkerboard_8x8)

# normalized_value = max_value − min_value / value − min_value

# first create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)
print("\nOriginal Matrix:")
print(random_matrix)

# Find the minimum and maximum values of the matrix
min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

# Normalize the matrix 
normalized_matrix = (random_matrix - min_value) / (max_value - min_value)

print("\nNormalized Matrix:")
print(normalized_matrix)

Checkerboard using np.tile
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

Original Matrix:
[[0.71760211 0.25036171 0.87660968 0.80843638 0.72115395]
 [0.48358228 0.86391935 0.70831965 0.46888454 0.27478722]
 [0.07796253 0.37532628 0.4908535  0.2628712  0.93266127]
 [0.89221658 0.99464151 0.71642805 0.37089411 0.35969212]
 [0.86898465 0.66957698 0.65539249 0.34730992 0.7710135 ]]

Normalized Matrix:
[[0.69777925 0.18806931 0.87123973 0.79686986 0.70165393]
 [0.44248833 0.85739592 0.68765307 0.42645465 0.21471496]
 [0.         0.32439246 0.45042046 0.20171584 0.93238609]
 [0.88826521 1.         0.69649848 0.31955744 0.30733724]
 [0.86292163 0.64538891 0.62991513 0.29382957 0.75604545]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
    
25. Given a 1D array, negate all elements which are between 3 and 8, in place. 
    


In [56]:
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])

print(color)


# Create a 5x3 matrix
matrix1 = np.random.rand(5, 3)

# Create a 3x2 matrix
matrix2 = np.random.rand(3, 2)

# Perform matrix multiplication
result = np.dot(matrix1, matrix2)

print("\nResult of matrix multiplication:\n",result)


# Create a 1D array
array = np.array([3, 4, 6, 5, 5, 7, 8, 9])

# Negate elements between 3 and 8
x=array[(array > 3) & (array < 8)] * -1

print("\nArray after negating elements between 3 and 8:")
print(x)



[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]

Result of matrix multiplication:
 [[0.920164   0.86285201]
 [0.90218843 0.61995207]
 [0.7999115  1.22904437]
 [0.55032121 0.47251446]
 [0.80237414 0.81173615]]

Array after negating elements between 3 and 8:
[-4 -6 -5 -5 -7]


27. What is the output of the following script?

print(sum(range(5),-1))  
from numpy import *  
print(sum(range(5),-1))  

In [57]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal?

In [63]:
# assign Z a value
Z=2

# play around with print, if no error it means all are legal
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

4
2
False
2j
2.0
False


28. What are the result of the following expressions? 

np.array(0) / np.array(0)  
np.array(0) // np.array(0)  
np.array([np.nan]).astype(int).astype(float)  

In [64]:

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/var/folders/np/h_r8frds63z84q8kndjycxt40000gn/T/ipykernel_11713/1119427974.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/var/folders/np/h_r8frds63z84q8kndjycxt40000gn/T/ipykernel_11713/1119427974.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/var/folders/np/h_r8frds63z84q8kndjycxt40000gn/T/ipykernel_11713/1119427974.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

29.  How to round away from zero a float array ?
  
30.  How to find common values between two arrays?
    
31.  How to ignore all numpy warnings (not recommended)? 
    
32.  Is the following expressions true?   
        np.sqrt(-1) == np.emath.sqrt(-1)

In [66]:
print("To round away from zero a float array, you can use numpy.ceil()\n")

print("To find common values between two arrays, you can use numpy.intersect1d() function\n")

print("To ignore all NumPy warnings use the numpy.seterr() function with the all parameter set to 'ignore")
np.seterr(all='ignore')

np.sqrt(-1) == np.emath.sqrt(-1)

To round away from zero a float array, you can use numpy.ceil()

To find common values between two arrays, you can use numpy.intersect1d() function

To ignore all NumPy warnings use the numpy.seterr() function with the all parameter set to 'ignore


False

33.  How to get the dates of yesterday, today and tomorrow? 

34.  How to get all the dates corresponding to the month of July 2016? 

35.  How to compute ((A+B)*(-A/2)) in place (without copy)? 



In [76]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print("yesterday was",yesterday)
print("today is", today)
print("tomorrow will be", tomorrow)

# How to get all the dates corresponding to the month of July 2016?
newdate = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("\n Dates coresponding to 2016-07 include:\n",newdate)


# How to compute ((A+B)*(-A/2)) in place (without copy)?

# Define arrays A and B
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A = A*(-0.5)
A = A + B 
result = A

print("\nResult is",result)


yesterday was 2024-02-22
today is 2024-02-23
tomorrow will be 2024-02-24

 Dates coresponding to 2016-07 include:
 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']

Result is [3.5 4.  4.5]


36.  Extract the integer part of a random array of positive numbers using 4 different methods 

37.  Create a 5x5 matrix with row values ranging from 0 to 4

In [79]:
# Create a random array 
random_array = np.random.rand(5, 5) * 6

# using np.floor()
integer_part = np.floor(random_array)

print("\nInteger part using np.floor():")
print(integer_part)


# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))

print("\n5x5 matrix with row values ranging from 0 to 4:")
print(matrix)


Integer part using np.floor():
[[4. 2. 3. 4. 2.]
 [1. 2. 4. 4. 4.]
 [2. 0. 3. 3. 4.]
 [2. 4. 4. 3. 4.]
 [2. 2. 2. 1. 5.]]

5x5 matrix with row values ranging from 0 to 4:
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


38.  Consider a generator function that generates 10 integers and use it to build an array 

39.  Create a vector of size 10 with values ranging from 0 to 1, both excluded  

In [81]:
# Generator function to generate 10 integers
def generate_integers():
    for i in range(10):
        yield i

# build an array using the generator function
array_from_generator = np.fromiter(generate_integers(), dtype=int)

print("Array from the generator function:\n",array_from_generator)

# Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector = np.linspace(0, 1, 12)[1:-1]

print("\nVector of size 10 with values ranging from 0 to 1, both excluded:\n",vector)


Array from the generator function:
 [0 1 2 3 4 5 6 7 8 9]

Vector of size 10 with values ranging from 0 to 1, both excluded:
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40.  Create a random vector of size 10 and sort it 
   
41.  How to sum a small array faster than np.sum?

In [86]:
random_vector = np.random.rand(10)
sorted_vector = np.sort(random_vector)

print("Random vector of size 10:")
print(random_vector)
print("\nSorted vector:")
print(sorted_vector,"\n")


# How to sum a small array faster than np.sum?
small_array = np.array([1, 2, 3, 4, 5])

# Using np.add.reduce()
sum_using_np_add_reduce = np.add.reduce(small_array)

print("Sum using np.add.reduce() = ", sum_using_np_add_reduce)

Random vector of size 10:
[0.78956416 0.41640442 0.53832558 0.94560995 0.47416288 0.71184284
 0.68450692 0.87439876 0.80610976 0.12787425]

Sorted vector:
[0.12787425 0.41640442 0.47416288 0.53832558 0.68450692 0.71184284
 0.78956416 0.80610976 0.87439876 0.94560995] 

Sum using np.add.reduce() =  15


42.  Consider two random array A and B, check if they are equal 
   
43.  Make an array immutable (read-only)

In [87]:
A = np.random.rand(5)
B = np.random.rand(5)

print("Array A:", A)
print("Array B:", B)

if np.array_equal(A, B):
    print("\nArrays A and B are equal.")
else:
    print("\nArrays A and B are not equal.")
    

# Make an array immutable (read-only)
readonly = np.zeros(10)
readonly.flags.writeable = False
readonly[0] = 1

Array A: [0.58149535 0.1028402  0.89301237 0.96140211 0.24462165]
Array B: [0.79225117 0.3126141  0.26358707 0.85763386 0.9979705 ]

Arrays A and B are not equal.


ValueError: assignment destination is read-only

44.  Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 


In [90]:
randmatrix = np.random.random((10,2))
X,Y = randmatrix[:,0], randmatrix[:,1]
radius = np.sqrt(X**2+Y**2)
teeta = np.arctan2(Y,X)
print("radius = ",radius)
print("\nteeta = ",teeta)

radius =  [0.47896739 0.6346416  0.88997083 0.32945725 0.76752407 0.87209972
 1.06884634 0.61137759 0.54959451 0.49353374]

teeta =  [1.14410173 1.49113692 0.20164947 0.72651775 0.2568239  0.32999836
 0.87747939 1.55990863 1.02500005 0.21081745]


45. Create random vector of size 10 and replace the maximum value by 0  

In [91]:
# Create a random vector of size 10
random_vector = np.random.rand(10)
print("Random vector:\n",random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("\nRandom vector after replacing the maximum value with 0:")
print(random_vector)


Random vector:
 [0.26900871 0.41640597 0.13578997 0.02329087 0.80549615 0.29080546
 0.13197572 0.10046415 0.59399745 0.26296215]

Random vector after replacing the maximum value with 0:
[0.26900871 0.41640597 0.13578997 0.02329087 0.         0.29080546
 0.13197572 0.10046415 0.59399745 0.26296215]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [92]:
str_array = np.zeros((5,5), [('x',float),('y',float)])
str_array['x'], str_array['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

# print result
print(str_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)

In [93]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix using broadcasting
C = 1 / (X[:, np.newaxis] - Y)

print("Cauchy matrix:")
print(C)


Cauchy matrix:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


48.  Print the minimum and maximum representable value for each numpy scalar type 

49.  How to print all the values of an array?

In [95]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
print("\nuse np.set_printoptions() to print all values in array")

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16

use np.set_printoptions() to print all values in array


50. How to find the closest value (to a given scalar) in a vector? 

In [97]:
closest_value = np.arange(10)
v = np.random.uniform(0,10)
index = (np.abs(closest_value-v)).argmin()

# print result
print(closest_value[index])

8


51.  Create a structured array representing a position (x,y) and a color (r,g,b) 


In [5]:
import numpy as np

# Define the dtype for the structured array
dtype = [('position', [('x', float), ('y', float)]), 
         ('color', [('r', int), ('g', int), ('b', int)])]

# Create a structured array
struc_array = np.zeros(1, dtype=dtype)

# Assign values to the structured array. position (x, y) & color (r, g, b)
struc_array['position'] = (10.0, 20.0) 
struc_array['color'] = (255, 0, 0)      

print(struc_array)

[((10., 20.), (255, 0, 0))]


52.  Consider a random vector with shape (100,2) representing coordinates, find point by point distances 

In [8]:
import numpy as np

random_vector = np.random.random((100, 2))

# Calculate point-by-point distances
distances = np.zeros((100, 100))  

for i in range(100):
    for j in range(100):
        distances[i, j] = np.sqrt(np.sum((random_vector[i] - random_vector[j])**2))


print(distances)


[[0.         0.76306973 0.35355583 ... 0.50399899 0.6258     0.69183636]
 [0.76306973 0.         0.45872408 ... 0.85603963 0.89764081 0.08301941]
 [0.35355583 0.45872408 0.         ... 0.687452   0.78407495 0.3778301 ]
 ...
 [0.50399899 0.85603963 0.687452   ... 0.         0.12406623 0.82433168]
 [0.6258     0.89764081 0.78407495 ... 0.12406623 0.         0.87640111]
 [0.69183636 0.08301941 0.3778301  ... 0.82433168 0.87640111 0.        ]]


53. How to convert a float (32 bits) array into an integer (32 bits) in place?
    
54. How to read the following file?   
1, 2, 3, 4, 5  
6,  ,  , 7, 8  
 ,  , 9,10,11  

In [11]:
# Create a float array (32 bits)
float_array = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)

# Convert the float array to an integer array (32 bits) in place
integer_array = float_array.view(dtype=np.int32)

print("Integer array:", integer_array)

#Q54 
# Read the file using the code below

# data = np.genfromtxt('file_path.csv', delimiter=',', dtype=np.float, filling_values=np.nan)




Integer array: [1066192077 1074580685 1079194419 1082969293]


55. What is the equivalent of enumerate for numpy arrays?    
    
    **The equivalent of enumerate for NumPy arrays is the np.ndenumerate function.**

56. Generate a generic 2D Gaussian-like array

In [18]:
import numpy as np

size = 5
sigma = 1.0

# Create grid of coordinates
x, y = np.meshgrid(np.linspace(-3, 3, size), np.linspace(-3, 3, size))

# Compute Gaussian values
gaussian = np.exp(-(x**2 + y**2) / (2 * sigma**2))

print(gaussian)


[[1.23409804e-04 3.60656314e-03 1.11089965e-02 3.60656314e-03
  1.23409804e-04]
 [3.60656314e-03 1.05399225e-01 3.24652467e-01 1.05399225e-01
  3.60656314e-03]
 [1.11089965e-02 3.24652467e-01 1.00000000e+00 3.24652467e-01
  1.11089965e-02]
 [3.60656314e-03 1.05399225e-01 3.24652467e-01 1.05399225e-01
  3.60656314e-03]
 [1.23409804e-04 3.60656314e-03 1.11089965e-02 3.60656314e-03
  1.23409804e-04]]


57. How to randomly place p elements in a 2D array?

In [24]:
n = 5
p = 3

elements = np.zeros((n,n))
np.put(elements, np.random.choice(range(n*n), p, replace=False),1)

print(elements)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix

In [26]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the mean of each row 
result_matrix = matrix - row_means

print("\nResult matrix after subtracting the mean of each row:\n",result_matrix)



Result matrix after subtracting the mean of each row:
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column?

In [31]:
srtarray = np.random.randint(0,10,(3,3))

print(srtarray)

# print sorted array
print("\nSorted array:")
print(srtarray[srtarray[:,1].argsort()])

[[2 4 1]
 [4 6 0]
 [9 2 7]]

Sorted array:
[[9 2 7]
 [2 4 1]
 [4 6 0]]


60. How to tell if a given 2D array has null columns?

In [36]:
import numpy as np

array = np.array([[1, 2, 0],
                  [4, 5, 0],
                  [7, 8, 0]])

# Check if any column contains only zeros
has_null_columns = np.any(np.all(array == 0, axis=0))

print("Does the array have null columns?", has_null_columns)


Does the array have null columns? True


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

In [39]:
import numpy as np

# Original array
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Window size
window_size = 4

# Calculate the number of rows in the resulting array
num_rows = len(Z) - window_size + 1

# Generate the resulting array
R = np.lib.stride_tricks.sliding_window_view(Z, (window_size,))

print(R)


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank

83. How to find the most frequent value in an array?

84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)

88. How to implement the Game of Life using numpy arrays?

89. How to get the n largest values of an array

In [38]:
Z = np.arange(50)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[45 46 47 48 49]


90.  Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)


In [98]:
import itertools

vector1 = [1, 2, 3]
vector2 = ['a', 'b', 'c']
vector3 = [True, False]

# Build the cartesian product
cartesian_product = list(itertools.product(vector1, vector2, vector3))

print("Cartesian product:\n",cartesian_product)


Cartesian product:
 [(1, 'a', True), (1, 'a', False), (1, 'b', True), (1, 'b', False), (1, 'c', True), (1, 'c', False), (2, 'a', True), (2, 'a', False), (2, 'b', True), (2, 'b', False), (2, 'c', True), (2, 'c', False), (3, 'a', True), (3, 'a', False), (3, 'b', True), (3, 'b', False), (3, 'c', True), (3, 'c', False)]


91. How to create a record array from a regular array? 

In [104]:

regular_array = np.array([(1, 'faty', 25),
                          (2, 'may', 30),
                          (3, 'ilu', 28)])

# Create a record array
record_array = np.rec.array(regular_array)

print("\nRecord array:")
print(record_array)



Record array:
[['1' 'faty' '25']
 ['2' 'may' '30']
 ['3' 'ilu' '28']]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [105]:
Z = np.random.rand(10)

# Method 1
Z_cubed_broadcasting = Z ** 3

# Method 2
Z_cubed_np_power = np.power(Z, 3)

# Method 3
Z_cubed_loop = np.zeros_like(Z)
for i in range(len(Z)):
    Z_cubed_loop[i] = Z[i] ** 3

print("Method 1 (Using broadcasting):")
print(Z_cubed_broadcasting)

print("\nMethod 2 (Using np.power() function):")
print(Z_cubed_np_power)

print("\nMethod 3 (Using a simple loop):")
print(Z_cubed_loop)


Method 1 (Using broadcasting):
[0.25194287 0.31251741 0.29346923 0.90239347 0.25581429 0.12473955
 0.26154399 0.09008415 0.01299555 0.17444473]

Method 2 (Using np.power() function):
[0.25194287 0.31251741 0.29346923 0.90239347 0.25581429 0.12473955
 0.26154399 0.09008415 0.01299555 0.17444473]

Method 3 (Using a simple loop):
[0.25194287 0.31251741 0.29346923 0.90239347 0.25581429 0.12473955
 0.26154399 0.09008415 0.01299555 0.17444473]


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 

In [111]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

print("Matrix A\n",A)
print("\nMatrix B\n",B)

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print("Rows\n",rows)

Matrix A
 [[4 2 1]
 [4 2 2]
 [3 3 1]
 [3 2 3]
 [1 3 4]
 [2 2 0]
 [3 1 3]
 [1 4 1]]

Matrix B
 [[2 4]
 [1 0]]
Rows
 [0 4 5 7]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [113]:
matrix = np.random.randint(0, 5, (10, 3))

# Extract rows with unequal values
unequal_rows = matrix[~np.all(matrix == matrix[0, :], axis=1)]

print("\nRows with unequal values:")
print(unequal_rows)



Rows with unequal values:
[[1 0 2]
 [0 2 4]
 [3 0 3]
 [0 1 4]
 [2 1 0]
 [4 2 1]
 [2 1 2]
 [0 1 3]
 [4 3 0]]


95. Convert a vector of ints into a matrix binary representation

In [116]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)

print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows?

In [117]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [1, 2, 3],
                     [7, 8, 9],
                     [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(array_2d, axis=0)

print("\nUnique rows:")
print(unique_rows)


Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


97.  Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 


In [119]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Inner product
inner_product = np.einsum('i,i->', A, B)
print("Inner product:", inner_product)

# Outer product
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:")
print(outer_product)

# Sum
sum_A = np.einsum('i->', A)
sum_B = np.einsum('i->', B)
print("Sum of A:", sum_A)
print("Sum of B:", sum_B)

# Element-wise multiplication
elementwise_multiplication = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:")
print(elementwise_multiplication)


Inner product: 32
Outer product:
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of A: 6
Sum of B: 15
Element-wise multiplication:
[ 4 10 18]


98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples 

In [120]:
X = np.array([0, 1, 3, 4, 6, 8, 9])
Y = np.array([0, 2, 3, 5, 7, 8, 10])

# Number of equidistant samples
num_samples = 10

equidistant_X = np.linspace(X[0], X[-1], num_samples)
equidistant_Y = np.interp(equidistant_X, X, Y)

# Print the equidistant samples
print("Equidistant X coordinates:")
print(equidistant_X)
print("\nEquidistant Y coordinates:")
print(equidistant_Y)


Equidistant X coordinates:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Equidistant Y coordinates:
[ 0.   2.   2.5  3.   5.   6.   7.   7.5  8.  10. ]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. 

In [121]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [122]:
# random 1D array
X = np.random.randn(100) 

# number of bootstrap samples
N = 1000 

#resample elements
idx = np.random.randint(0, X.size, (N, X.size))

# compute mean
means = X[idx].mean(axis=1)

confidence_interval = np.percentile(means, [2.5, 97.5])

print(confidence_interval)

[-0.10656874  0.27827704]
