## NUMPY PRACTICE EXERCISES

#### Source:
https://github.com/arewadataScience/ArewaDS-Machine-Learning/blob/main/100_numpy_exercise.md

1. Import the numpy package under the name np
2. Print the numpy version and the configuration

In [12]:
import numpy as np

# Print NumPy version and configuration
print("NumPy Version is:", np.__version__)
print("NumPy Configuration is:") 
print(np.show_config())



NumPy Version is: 1.26.2
NumPy Configuration is:
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21",
      "detection method": "pkgconfig",
      "include directory": "/Users/ruqayyanasiriro/miniconda3/envs/adsatesting/in

3. Create a null vector of size 10  
4. How to find the memory size of any array 

In [14]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)
print("Null vector of size 10:", null_vector)

# Find the memory size of any array taking null vector above as example
memory_size = null_vector.nbytes
print("Memory size of the array:", memory_size, "bytes")


Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Memory size of the array: 80 bytes


5. How to get the documentation of the numpy add function from the command line? 
   
  **ANSWER:** we use np.info(np.add). It will give the documentation of the 'add' function.
  
  
   
6. Create a null vector of size 10 but the fifth value which is 1 
   
7. Create a vector with values ranging from 10 to 49 
   
8.  Reverse a vector (first element becomes last)
   

In [17]:
import numpy as np

# Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector where 5th value is 1 =", null_vector)

# Create a vector with values ranging from 10 to 49 using np.arange()
vector_range = np.arange(10, 50)
print("\nVector with values ranging from 10 to 49 = ", vector_range)

# Reverse a vector using vector range from above
reversed_vector = np.flip(vector_range)
print("\nReversed vector is", reversed_vector)


Null vector where 5th value is 1 = [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Vector with values ranging from 10 to 49 =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed vector is [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 
    
10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
import numpy as np

# create 3x3 matrix, range 0-8
three_by_three = np.arange(0, 9).reshape(3,3)

# print result
print(three_by_three)

# given array
arr = np.array([1, 2, 0, 0, 4, 0])

#identifies the indices of elements that are non-zero.
indices_nonzero = np.nonzero(arr)

# prints output
print(indices_nonzero)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)


11.  Create a 3x3 identity matrix 
   
12.  Create a 3x3x3 array with random values

In [18]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
print("\n3x3x3 array:\n",random_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3x3 array:
 [[[0.64990161 0.93643386 0.67420505]
  [0.72361468 0.97651342 0.86096396]
  [0.88430237 0.59985661 0.82301981]]

 [[0.04475813 0.78127797 0.39957837]
  [0.95652449 0.37569051 0.06833121]
  [0.6452381  0.42273315 0.52667437]]

 [[0.13397625 0.10791948 0.0142508 ]
  [0.01976379 0.29985953 0.38714354]
  [0.77142603 0.3730331  0.90535606]]]


13.  Create a 10x10 array with random values and find the minimum and maximum values
   


In [16]:
# 10x10 array of random numbers and result
random_array_10 = np.random.rand(10,10)

print(random_array_10)

# prints min and max random generated number
print("\nmax value is",np.max(random_array_10))

print("\nmin value is",np.min(random_array_10))

[[0.72039015 0.09369841 0.72873494 0.22228938 0.06523871 0.61859414
  0.2845161  0.53928405 0.19231507 0.17979439]
 [0.95476376 0.37805859 0.17744809 0.28554068 0.73021984 0.02174129
  0.7452342  0.74529583 0.59142306 0.7688509 ]
 [0.13002406 0.68732518 0.85830626 0.33164867 0.26285724 0.9998481
  0.78274774 0.28837482 0.30349986 0.56336726]
 [0.46721595 0.51993929 0.24443317 0.80123172 0.5911429  0.04585177
  0.78965858 0.12381675 0.3533921  0.85838522]
 [0.08031602 0.27742856 0.41471596 0.54635581 0.53959118 0.32552491
  0.5469929  0.28072248 0.85583341 0.20865325]
 [0.20777889 0.38760232 0.39581088 0.70158354 0.44772252 0.35621967
  0.00200307 0.65369535 0.93456403 0.22712985]
 [0.78323234 0.06243504 0.92108338 0.3488049  0.27618782 0.36794066
  0.08020142 0.75477667 0.66412062 0.65979361]
 [0.2205282  0.07021136 0.78609665 0.68163825 0.81087067 0.50422584
  0.14202899 0.66101256 0.18697814 0.81771941]
 [0.90084349 0.66986758 0.18304613 0.72947978 0.07493001 0.11165066
  0.09381015 

14. Create a random vector of size 30 and find the mean value 
    
    

In [20]:
# Create a random vector of size 30 
random_vector = np.random.rand(30)

# prints result
print(random_vector)

# find the mean value 
mean_random_vector = np.sum(random_vector)/30

print("\nmean is:", mean_random_vector)

[0.82421224 0.70580617 0.80107379 0.03691118 0.30039325 0.46079249
 0.12953655 0.66014818 0.36088679 0.86813877 0.05934723 0.43572113
 0.49544336 0.74069737 0.10634164 0.51781306 0.98861544 0.58477368
 0.19868623 0.72809833 0.17228044 0.63112825 0.80056208 0.06001381
 0.11829353 0.76483987 0.70521921 0.1923012  0.67518834 0.76797108]

mean is: 0.49637448972654374


15. Create a 2d array with 1 on the border and 0 inside

16. How to add a border (filled with 0's) around an existing array?



In [29]:
import numpy as np

# dimensions of the 2D array as 3x3
rows, cols = 3, 3

# create a 2D array filled with zeros
array_2d = np.zeros((rows, cols))

# Set the border elements to 1
array_2d[0, :] = 1  # Top row
array_2d[-1, :] = 1  # Bottom row
array_2d[:, 0] = 1  # Leftmost column
array_2d[:, -1] = 1  # Rightmost column

print(array_2d)

# How to add a border (filled with 0's) around an existing array?
x = np.zeros((3, 3))

# Print result
print('\n Border filled with zeros\n',x)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

 Border filled with zeros
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


17. What is the result of the following expression? 

0 * np.nan  
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  
np.nan in set([np.nan])  
0.3 == 3 * 0.1  

In [30]:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal  

19. Create a 8x8 matrix and fill it with a checkerboard pattern
 

In [36]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set the values 1234 just below the diagonal
matrix[1, 0] = 1
matrix[2, 1] = 2
matrix[3, 2] = 3
matrix[4, 3] = 4

print("\n5 by 5 matrix\n",matrix)

# Create an 8x8 matrix filled with zeros
cmatrix = np.zeros((8, 8), dtype=int)

# Set even rows and even columns to 1 using slicing
cmatrix[::2, ::2] = 1

# Set odd rows and odd columns to 1 using slicing
cmatrix[1::2, 1::2] = 1

print("\nchekerboard matrix\n",cmatrix)




5 by 5 matrix
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]

chekerboard matrix
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


21. Create a checkerboard 8x8 matrix using the tile function

22. 

In [40]:
import numpy as np

# Create the checkerboard pattern
checkerboard = np.array([[0, 1], [1, 0]])

# Use np.tile() to create checkerboard pattern of 8x8 matrix
checkerboard_8x8 = np.tile(checkerboard, (4, 4))

print("Checkerboard using np.tile\n",checkerboard_8x8)


Checkerboard using np.tile
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
