## NUMPY PRACTICE EXERCISES

#### Source:
https://github.com/arewadataScience/ArewaDS-Machine-Learning/blob/main/100_numpy_exercise.md

1. Import the numpy package under the name np
2. Print the numpy version and the configuration

In [12]:
import numpy as np

# Print NumPy version and configuration
print("NumPy Version is:", np.__version__)
print("NumPy Configuration is:") 
print(np.show_config())



NumPy Version is: 1.26.2
NumPy Configuration is:
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.6",
      "commands": "arm64-apple-darwin20.0.0-clang++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas",
      "found": true,
      "version": "0.3.21",
      "detection method": "pkgconfig",
      "include directory": "/Users/ruqayyanasiriro/miniconda3/envs/adsatesting/in

3. Create a null vector of size 10  
4. How to find the memory size of any array 

In [14]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)
print("Null vector of size 10:", null_vector)

# Find the memory size of any array taking null vector above as example
memory_size = null_vector.nbytes
print("Memory size of the array:", memory_size, "bytes")


Null vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Memory size of the array: 80 bytes


5. How to get the documentation of the numpy add function from the command line? 
   
  **ANSWER:** we use np.info(np.add). It will give the documentation of the 'add' function.
  
  
   
6. Create a null vector of size 10 but the fifth value which is 1 
   
7. Create a vector with values ranging from 10 to 49 
   
8.  Reverse a vector (first element becomes last)
   

In [17]:
import numpy as np

# Create a null vector of size 10 but the fifth value which is 1
null_vector = np.zeros(10)
null_vector[4] = 1
print("Null vector where 5th value is 1 =", null_vector)

# Create a vector with values ranging from 10 to 49 using np.arange()
vector_range = np.arange(10, 50)
print("\nVector with values ranging from 10 to 49 = ", vector_range)

# Reverse a vector using vector range from above
reversed_vector = np.flip(vector_range)
print("\nReversed vector is", reversed_vector)


Null vector where 5th value is 1 = [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Vector with values ranging from 10 to 49 =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Reversed vector is [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 
    
10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
import numpy as np

# create 3x3 matrix, range 0-8
three_by_three = np.arange(0, 9).reshape(3,3)

# print result
print(three_by_three)

# given array
arr = np.array([1, 2, 0, 0, 4, 0])

#identifies the indices of elements that are non-zero.
indices_nonzero = np.nonzero(arr)

# prints output
print(indices_nonzero)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 1, 4]),)
